project/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^fs/status$', views.FileStatusView.as_view(), name='fs_status'),
    url(r'^fs/(?P<filename>[0-9a-f]*)$', views.FileView.as_view(), name='fs_status'),
    url(r'^jobs/take$', views.JobTakeView.as_view(), name='take_job'),
    url(r'^jobs/(?P<job_id>\d+)/result$', views.JobPutResultView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/state$', views.JobPutStateView.as_view()),

    url(r'^queue/$', views.QueueView.as_view(), name='queue')
]

project/irunner2/urls.py
from django.conf.urls import include, url
#from django.contrib import admin
import common.views
from django_js_reverse.views import urls_js
from django.views.decorators.cache import cache_page


urlpatterns = [
    url(r'^$', common.views.home, name='home'),
    url(r'^language/$', common.views.language, name='language'),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
    url(r'^storage/', include('storage.urls', namespace='storage')),
    url(r'^problems/', include('problems.urls', namespace='problems')),
    url(r'^compilers/', include('proglangs.urls', namespace='proglangs')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^', include('solutions.urls', namespace='solutions')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^contests/', include('contests.urls', namespace='contests')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^about/', common.views.about, name='about'),
    url('^', include('cauth.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
    url(r'^hall-of-fame/$', common.views.HallOfFameView.as_view(), name='hall_of_fame')
]

handler403 = 'common.views.error403'

project/problems/urls.py
from django.conf.urls import include, url

from . import views

problem_urlpatterns = [
    url(r'^$', views.ProblemOverviewView.as_view(), name='overview'),
    url(r'^statement/(?P<filename>.+)?$', views.ProblemStatementView.as_view(), name='statement'),

    url(r'^tests/$', views.ProblemTestsView.as_view(), name='tests'),
    url(r'^tests/(?P<test_number>[0-9]+)/$', views.ProblemTestsTestView.as_view(), name='show_test'),
    url(r'^tests/upload/$', views.ProblemTestsUploadArchiveView.as_view(), name='upload_archive'),
    url(r'^tests/new/$', views.ProblemTestsNewView.as_view(), name='new_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/edit/$', views.ProblemTestsTestEditView.as_view(), name='edit_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/delete/$', views.ProblemTestsDeleteView.as_view(), name='delete_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/image/(?P<filename>.+)$', views.ProblemTestsTestImageView.as_view(), name='test_image'),
    url(r'^tests/batch/set/time-limit/$', views.ProblemTestsSetTimeLimitView.as_view(), name='tests_mass_time_limit'),
    url(r'^tests/batch/set/memory-limit/$', views.ProblemTestsSetMemoryLimitView.as_view(), name='tests_mass_memory_limit'),

    url(r'^tests/open/input-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='input', download=False), name='test_input_open'),
    url(r'^tests/download/input-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='input', download=True), name='test_input_download'),
    url(r'^tests/open/answer-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='answer', download=False), name='test_answer_open'),
    url(r'^tests/download/answer-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='answer', download=True), name='test_answer_download'),

    url(r'^solutions/$', views.ProblemSolutionsView.as_view(), name='solutions'),

    url(r'^files/$', views.ProblemFilesView.as_view(), name='files'),
    url(r'^files/data/(?P<file_id>[0-9]+)/open/(?P<filename>.+)$', views.ProblemFilesFileOpenView.as_view(), name='data_file_open'),
    url(r'^files/data/(?P<file_id>[0-9]+)/download/(?P<filename>.+)$', views.ProblemFilesFileOpenView.as_view(download=True), name='data_file_download'),
    url(r'^files/data/(?P<file_id>[0-9]+)/edit/$', views.ProblemFilesDataFileEditView.as_view(), name='data_file_edit'),
    url(r'^files/data/(?P<file_id>[0-9]+)/delete/$', views.ProblemFilesDataFileDeleteView.as_view(), name='data_file_delete'),
    url(r'^files/data/new/$', views.ProblemFilesDataFileNewView.as_view(), name='data_file_new'),

    url(r'^files/source/(?P<file_id>[0-9]+)/open/(?P<filename>.+)$', views.ProblemFilesSourceFileOpenView.as_view(), name='source_file_open'),
    url(r'^files/source/(?P<file_id>[0-9]+)/download/(?P<filename>.+)$', views.ProblemFilesSourceFileOpenView.as_view(download=True), name='source_file_download'),
    url(r'^files/source/(?P<file_id>[0-9]+)/edit/$', views.ProblemFilesSourceFileEditView.as_view(), name='source_file_edit'),
    url(r'^files/source/(?P<file_id>[0-9]+)/delete/$', views.ProblemFilesSourceFileDeleteView.as_view(), name='source_file_delete'),
    url(r'^files/source/new/$', views.ProblemFilesSourceFileNewView.as_view(), name='source_file_new'),

    url(r'^tex/$', views.ProblemTeXView.as_view(), name='tex'),
    url(r'^tex/render/$', views.ProblemTeXRenderView.as_view(), name='tex_render'),
    url(r'^tex/new/statement/$', views.ProblemTeXNewStatementView.as_view(), name='tex_new_statement'),
    url(r'^tex/(?P<file_id>[0-9]+)/$', views.ProblemTeXEditView.as_view(), name='edit_tex'),
    url(r'^tex/(?P<file_id>[0-9]+)/(?P<filename>.+)$', views.ProblemTeXEditRelatedFileView.as_view()),

    url(r'^challenges/$', views.ProblemChallengesView.as_view(), name='challenges'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/$', views.ProblemChallengeView.as_view(), name='challenge'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/status/json/$', views.ProblemChallengeJsonView.as_view(), name='challenge_status_json'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/open/(?P<resource_id>[0-9a-f]*)$', views.ProblemChallengeDataView.as_view(), name='challenge_data'),
    url(r'^challenges/new/$', views.ProblemNewChallengeView.as_view(), name='new_challenge'),

    url(r'^submit/$', views.ProblemSubmitView.as_view(), name='submit'),
    url(r'^submission/(?P<solution_id>[0-9]+)/$', views.ProblemSubmissionView.as_view(), name='submission'),
    url(r'^folders/$', views.ProblemFoldersView.as_view(), name='folders'),
    url(r'^properties/$', views.ProblemPropertiesView.as_view(), name='properties'),
    url(r'^pictures/$', views.ProblemPicturesView.as_view(), name='pictures'),
    url(r'^validator/$', views.ProblemValidatorView.as_view(), name='validator'),
]

urlpatterns = [
    url(r'^tree/$', views.ShowTreeView.as_view(), name='show_tree'),
    url(r'^tree/(?P<folder_id>[0-9]+)/$', views.ShowTreeFolderView.as_view(), name='show_tree_folder'),
    url(r'^tree/(?P<folder_id>[0-9]+)/json/$', views.ShowTreeFolderJsonView.as_view(), name='show_tree_folder_json'),

    url(r'^(?P<problem_id>[0-9]+)/', include(problem_urlpatterns)),

    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/$', views.ShowFolderView.as_view(), name='show_folder'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/new/folder/$', views.CreateFolderView.as_view(), name='create_folder'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/properties/$', views.UpdateFolderView.as_view(), name='folder_properties'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/delete/$', views.DeleteFolderView.as_view(), name='delete_folder'),

    url(r'^search/$', views.SearchView.as_view(), name='search'),

    url(r'^tex/$', views.TeXView.as_view(), name='tex_playground'),
    url(r'^tex/render/$', views.TeXRenderView.as_view(), name='tex_playground_render'),
]

project/solutions/urls.py
from django.conf.urls import include, url

from . import views

solutions_urlpatterns = [
    url(r'^$', views.SolutionListView.as_view(), name='list'),

    url(r'^(?P<solution_id>[0-9]+)/$', views.SolutionMainView.as_view(), name='main'),
    url(r'^(?P<solution_id>[0-9]+)/source/$', views.SolutionSourceView.as_view(), name='source'),
    url(r'^(?P<solution_id>[0-9]+)/log/$', views.SolutionLogView.as_view(), name='log'),
    url(r'^(?P<solution_id>[0-9]+)/tests/$', views.SolutionTestsView.as_view(), name='tests'),
    url(r'^(?P<solution_id>[0-9]+)/runs/$', views.SolutionJudgementsView.as_view(), name='judgements'),
    url(r'^(?P<solution_id>[0-9]+)/attempts/$', views.SolutionAttemptsView.as_view(), name='attempts'),
    url(r'^(?P<solution_id>[0-9]+)/status/json/$', views.SolutionStatusJsonView.as_view(), name='status_json'),

    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/$', views.SolutionTestCaseResultView.as_view(), name='test_case_result'),
    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/(?P<mode>input|output|answer|stdout|stderr)\.txt$', views.SolutionTestCaseResultDataView.as_view(), name='test_data'),
    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/images/(?P<filename>.*)$', views.SolutionTestCaseResultImageView.as_view(), name='test_image'),

    url(r'^(?P<solution_id>[0-9]+)/source/open/(?P<filename>.*)$', views.SolutionSourceOpenView.as_view(), name='source_open'),
    url(r'^(?P<solution_id>[0-9]+)/source/download/(?P<filename>.*)$', views.SolutionSourceDownloadView.as_view(), name='source_download'),

    url(r'^delete/$', views.DeleteSolutionsView.as_view(), name='delete'),

    url(r'^compare/$', views.CompareSolutionsView.as_view(), name='compare'),
]

judgements_urlpatterns = [
    url(r'^$', views.JudgementListView.as_view(), name='judgement_list'),
    url(r'^(?P<judgement_id>[0-9]+)/$', views.JudgementView.as_view(), name='show_judgement'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/$', views.JudgementTestCaseResultView.as_view(), name='judgement_testcaseresult'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/(?P<mode>input|output|answer|stdout|stderr)\.txt$', views.JudgementTestCaseResultDataView.as_view(), name='judgement_testdata'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/images/(?P<filename>.*)$', views.JudgementTestCaseResultImageView.as_view(), name='judgement_testimage'),
]

rejudges_urlpatterns = [
    url(r'^new/$', views.CreateRejudgeView.as_view(), name='create_rejudge'),
    url(r'^(?P<rejudge_id>[0-9]+)/$', views.RejudgeView.as_view(), name='rejudge'),
    url(r'^(?P<rejudge_id>[0-9]+)/status/json/$', views.RejudgeJsonView.as_view(), name='rejudge_status_json'),
    url(r'^$', views.RejudgeListView.as_view(), name='rejudge_list'),
]

urlpatterns = [
    url(r'^solutions/', include(solutions_urlpatterns)),
    url(r'^runs/', include(judgements_urlpatterns)),
    url(r'^rejudges/', include(rejudges_urlpatterns)),
]

project/problems/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _

from mptt.models import MPTTModel, TreeForeignKey

from common.outcome import Outcome
from proglangs.models import Compiler
from storage.models import FileMetadataBase
from storage.storage import ResourceIdField


class ProblemFolder(MPTTModel):
    name = models.CharField(_('name'), max_length=64)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

    def __unicode__(self):
        return self.name


class Problem(models.Model):
    number = models.IntegerField(_('number'), blank=True, null=True, default=None)
    subnumber = models.IntegerField(_('subnumber'), blank=True, null=True, default=None)
    full_name = models.CharField(_('full name'), max_length=200, blank=True)
    short_name = models.CharField(_('short name'), max_length=32, blank=True)
    difficulty = models.IntegerField(_('difficulty'), blank=True, null=True, default=None)

    input_filename = models.CharField(_('input file name'), max_length=32, blank=True)
    output_filename = models.CharField(_('output file name'), max_length=32, blank=True)

    folders = models.ManyToManyField(ProblemFolder, verbose_name=_('folders'))

    class Meta:
        ordering = ['number', 'subnumber', 'full_name']

    def get_formatted_number(self):
        if self.number is None:
            return u''
        if self.subnumber is None:
            return u'{0}'.format(self.number)
        else:
            return u'{0}.{1}'.format(self.number, self.subnumber)

    def _numbered_name(self, name):
        if self.number is not None:
            if name:
                return u'{0}. {1}'.format(self.get_formatted_number(), name)
            else:
                return self.get_formatted_number()
        else:
            return name

    def numbered_full_name(self):
        return self._numbered_name(self.full_name)

    def numbered_full_name_difficulty(self):
        result = self.numbered_full_name()
        if self.difficulty is not None:
            return u'[{0}] {1}'.format(self.difficulty, result)
        else:
            return result

    def numbered_short_name(self):
        return self._numbered_name(self.short_name)

    # for contests
    def unnumbered_brief_name(self):
        if self.short_name:
            return self.short_name
        elif self.full_name:
            return self.full_name
        else:
            return self.numbered_full_name()


class ProblemExtraInfo(models.Model):
    problem = models.OneToOneField(Problem, null=False, on_delete=models.CASCADE, primary_key=True)
    description = models.TextField(_('description'), blank=True)  # public
    hint = models.TextField(_('hint'), blank=True)  # private


class ProblemRelatedFile(FileMetadataBase):
    STATEMENT_TEX = 211
    STATEMENT_HTML = 212
    ADDITIONAL_STATEMENT_FILE = 213
    SOLUTION_DESCRIPTION = 214
    SAMPLE_INPUT_FILE = 220
    SAMPLE_OUTPUT_FILE = 221
    USER_FILE = 222

    FILE_TYPE_CHOICES = (
        (STATEMENT_TEX, _('TeX statement')),
        (STATEMENT_HTML, _('HTML statement')),
        (ADDITIONAL_STATEMENT_FILE, _('Additional statement file')),
        (SOLUTION_DESCRIPTION, _('Solution description')),
        (SAMPLE_INPUT_FILE, _('Sample input file')),
        (SAMPLE_OUTPUT_FILE, _('Sample output file')),
        (USER_FILE, _('User file')),
    )

    TEST_CASE_IMAGE_FILE_TYPES = (
        ADDITIONAL_STATEMENT_FILE,
        SAMPLE_INPUT_FILE,
        SAMPLE_OUTPUT_FILE,
        USER_FILE,
    )
    TEX_FILE_TYPES = (
        STATEMENT_TEX,
    )

    problem = models.ForeignKey(Problem)
    file_type = models.IntegerField(_('file type'), choices=FILE_TYPE_CHOICES)
    description = models.TextField(_('description'), blank=True)

    class Meta:
        unique_together = ('problem', 'filename')


class ProblemRelatedSourceFile(FileMetadataBase):
    AUTHORS_SOLUTION = 215
    CHECKER = 216
    CONTESTANT_SOLUTION = 217
    GENERATOR = 218
    LIBRARY = 219
    VALIDATOR = 223

    FILE_TYPE_CHOICES = (
        (AUTHORS_SOLUTION, _('Author\'s solution')),
        (CHECKER, _('Checker')),
        (CONTESTANT_SOLUTION, _('Contestant solution')),
        (GENERATOR, _('Generator')),
        (LIBRARY, _('Library')),
        (VALIDATOR, _('Validator')),
    )

    # null for global checkers
    problem = models.ForeignKey(Problem, null=True)
    file_type = models.IntegerField(_('file type'), choices=FILE_TYPE_CHOICES)
    description = models.TextField(_('description'), blank=True)
    compiler = models.ForeignKey(Compiler, verbose_name=_('compiler'))

    class Meta:
        unique_together = ('problem', 'filename')


class TestCase(models.Model):
    problem = models.ForeignKey(Problem)
    ordinal_number = models.PositiveIntegerField(_('number'), default=0)
    description = models.TextField(_('description'), blank=True)

    input_resource_id = ResourceIdField()
    input_size = models.IntegerField(default=0)

    answer_resource_id = ResourceIdField()
    answer_size = models.IntegerField(default=0)

    time_limit = models.IntegerField()
    memory_limit = models.IntegerField(default=0)
    points = models.IntegerField(default=1)

    class Meta:
        unique_together = ('problem', 'ordinal_number')

    def set_input(self, storage, f):
        resource_id = storage.save(f)
        updated = (self.input_resource_id != resource_id)
        self.input_resource_id = resource_id
        self.input_size = f.size
        return updated

    def set_answer(self, storage, f):
        resource_id = storage.save(f)
        updated = (self.answer_resource_id != resource_id)
        self.answer_resource_id = resource_id
        self.answer_size = f.size
        return updated


class Validation(models.Model):
    problem = models.OneToOneField(Problem)
    is_pending = models.BooleanField(default=False)
    validator = models.ForeignKey(ProblemRelatedSourceFile, null=True, blank=True, on_delete=models.SET_NULL)
    general_failure_reason = models.CharField(max_length=64, blank=True)


class TestCaseValidation(models.Model):
    validation = models.ForeignKey(Validation)
    input_resource_id = ResourceIdField()
    is_valid = models.BooleanField()
    validator_message = models.CharField(max_length=255, blank=True)

project/problems/templates/problems/irunner_problems_difficulty_tag.html
<div class="ir-difficultybox{% if used %} ir-difficultybox-used{% endif %}">{% if difficulty %}{{ difficulty }}{% else %}&nbsp;{% endif %}</div>

project/problems/templates/problems/irunner_problems_io_tag.html
<span class="ir-monospace">{% if emph %}<em>{% endif %}{{ filename }}{% if emph %}</em>{% endif %}</span>

project/problems/templates/problems/show_test.html
{% extends "problems/base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_problems %}
{% load irunner_storage %}

{% block main %}

{% bootstrap_messages %}

<nav>
    <ul class="pagination ir-pagination-no-margin">
        <li>
            <a href="{% url 'problems:show_test' problem_id prev_test %}{{ navigator.query_string }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li>
            <a href="{% url 'problems:tests' problem_id %}{{ navigator.query_string }}">
                {% trans 'Test' %} {{ current_test }} {% trans 'of' %} {{ total_tests }}
            </a>
        </li>
        <li>
            <a href="{% url 'problems:show_test' problem_id next_test %}{{ navigator.query_string }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
    <ul class="pagination ir-pagination-no-margin">
        <li>
            <a href="{% url 'problems:edit_test' problem_id current_test %}{{ navigator.query_string }}">
                {% bootstrap_icon 'pencil' %} <span class="ir-icon-label">{% trans 'Edit' %}</span>
            </a>
        </li>
        <li>
            <a href="#" data-toggle="modal" data-target="#myModal">
                {% bootstrap_icon 'trash' %} <span class="ir-icon-label">{% trans 'Delete' %}</span>
            </a>
        </li>
    </ul>
</nav>

<table class="ir-test-info">
    <tbody>
        <tr>
            <td>{% trans 'Score' %}</td>
            <td>{{ points }}</td>
        </tr>
        <tr>
            <td>{% trans 'Time limit' %}</td>
            <td>{% irunner_problems_timelimit time_limit %}</td>
        </tr>
        <tr>
            <td>{% trans 'Memory limit' %}</td>
            <td>{% irunner_problems_memorylimit memory_limit %}</td>
        </tr>
        {% if description.text %}
            <tr>
                <td>{% trans 'Description' %}</td>
                <td>{{ description.text|linebreaksbr }}</td>
            </tr>
        {% endif %}
    </tbody>
</table>

{% if description.images %}
    {% if description.images %}
        {% for filename in description.images %}
            <div class="ir-imagebox">
                <div>
                    <div>
                        {% url 'problems:test_image' problem.id current_test filename as img_url %}
                        <a href="{{ img_url }}"><img src="{{ img_url }}" alt="{{ filename }}"></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endif %}

<div class="row">
    <div class="col-md-6">
        <h4>
            <a href="{% url 'problems:test_input_open' problem.id current_test %}" title="{% trans 'Open' %}">{% bootstrap_icon 'open-file' %}</a>
            <a href="{% url 'problems:test_input_download' problem.id current_test %}" title="{% trans 'Download' %}">{% bootstrap_icon 'download-alt' %}</a>
            {% irunner_problems_inputfile problem.input_filename %}
            <span class="ir-file-size">[{{ input_repr.size|filesizeformat }}]</span>
        </h4>
        {% irunner_storage_show input_repr %}
    </div>
    <div class="col-md-6">
        <h4>
            <a href="{% url 'problems:test_answer_open' problem.id current_test %}" title="{% trans 'Open' %}">{% bootstrap_icon 'open-file' %}</a>
            <a href="{% url 'problems:test_answer_download' problem.id current_test %}" title="{% trans 'Download' %}">{% bootstrap_icon 'download-alt' %}</a>
            {% irunner_problems_outputfile problem.output_filename %}
            <span class="ir-file-size">[{{ answer_repr.size|filesizeformat }}]</span>
        </h4>
        {% irunner_storage_show answer_repr %}
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">{% trans 'Confirm' %}</h4>
            </div>
            <div class="modal-body">
                {% trans 'Test case is going to be deleted.' %}
            </div>

            <div class="modal-footer">
                <form method="post" action="{% url 'problems:delete_test' problem.id current_test %}{{ navigator.query_string }}">
                    {% csrf_token %}
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cancel' %}</button>
                    <button type="submit" class="btn btn-danger">{% trans 'Delete' %}</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project/problems/templates/problems/submission.html
{% extends 'problems/base.html' %}

{% load irunner_solutions %}

{% block main %}
    {% irunner_solutions_livesubmission solution_id %}
{% endblock %}

project/problems/templates/problems/texs.html
{% extends 'problems/base.html' %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_proglangs %}

{% block main %}
    <table class="table table-condensed table-hover table-bordered ir-problem-files-table">
        <thead>
            <tr>
                <th class="ir-col-filename">{% trans 'File' %}</th>
                <th class="ir-col-filetype">{% trans 'Type' %}</th>
            </tr>
        </thead>
        <tbody>
        {% for f in related_files %}
            <tr>
                <td class="ir-col-filename">
                    <a href="{% url 'problems:edit_tex' problem.id f.id %}{{ navigator.query_string }}">{{ f.filename }}</a> <span class="ir-file-size">[{{ f.size|filesizeformat }}]</span>
                </td>
                <td class="ir-col-filetype">{{ f.get_file_type_display }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% buttons %}
        <a href="{% url 'problems:tex_new_statement' problem.id %}{{ navigator.query_string }}" class="btn btn-default">{% bootstrap_icon 'plus' %} <span class="ir-icon-label">{% trans 'New statement' %}</span></a>
        <a href="#" class="btn btn-default disabled">{% bootstrap_icon 'plus' %} <span class="ir-icon-label">{% trans 'New editorial' %}</span></a>
    {% endbuttons %}
{% endblock %}

project/problems/templates/problems/tree.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block title %}{% trans 'Problems' %}{% endblock %}

{% block head %}
    <link href="{% static 'fancytree-2.13.0/skin-win8/ui.fancytree.min.css' %}" rel="stylesheet">
    <link href="{% static 'DataTables-1.10.10/media/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'jquery-ui-1.11.4.custom/jquery-ui.min.js' %}"></script>
    <script src="{% static 'fancytree-2.13.0/jquery.fancytree-all.min.js' %}"></script>
    <script src="{% static 'DataTables-1.10.10/media/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'DataTables-1.10.10/media/js/dataTables.bootstrap.min.js' %}"></script>
{% endblock %}

{% block content %}

{% get_current_language as LANGUAGE_CODE %}

<script>
var irSourceData = {{ tree_data|safe }};

function setFolderHeader(json) {
    var name = json["name"] || "";
    $("#foldername").text(name);

    var id = json["id"];
    if (id) {
        var urlMask = "{% url 'problems:show_tree_folder' 12345 %}".replace(/12345/, id);
        history.pushState({}, name, urlMask);
    }
}

$(document).ready(function() {
    $("#datatable").DataTable({
        "language": {
            "url": "{% static 'DataTables-1.10.10/i18n' %}/{{ LANGUAGE_CODE }}.json"
        },
        "autoWidth": false,
        {% if table_data %}
            "data": {{ table_data|safe }}
        {% endif %}
    });

    var fancyTree = $("#tree").fancytree({
        source: irSourceData
    });

    {% if cur_folder_id %}
        $("#tree").fancytree("getTree").activateKey("{{ cur_folder_id }}");
    {% endif %}

    fancyTree.bind("fancytreeactivate", function(event, data) {
        var node = data.node;
        var urlMask = "{% url 'problems:show_tree_folder_json' 12345 %}".replace(/12345/, node.key.toString());
        $("#datatable").dataTable().api().ajax.url(urlMask).load(setFolderHeader);
    });
});
</script>

<div class="row">
    <div class="col-md-3">
        <div id="tree"></div>
    </div>
    <div class="col-md-9">
        <h3 id="foldername">{{ cur_folder_name }}</h3>
        <table id="datatable" class="table table-striped table-condensed table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Full Name</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

{% endblock %}

project/problems/templates/problems/validator.html
{% extends 'problems/base.html' %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_proglangs %}
{% load staticfiles %}

{% block main %}
    <form method="post">
        {% bootstrap_form form %}
        {% csrf_token %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">{% trans 'Revalidate testset' %}</button>
        {% endbuttons %}
    </form>
{% endblock %}