project/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^fs/status$', views.FileStatusView.as_view(), name='fs_status'),
    url(r'^fs/(?P<filename>[0-9a-f]*)$', views.FileView.as_view(), name='fs_status'),
    url(r'^jobs/take$', views.JobTakeView.as_view(), name='take_job'),
    url(r'^jobs/(?P<job_id>\d+)/result$', views.JobPutResultView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/state$', views.JobPutStateView.as_view()),

    url(r'^queue/$', views.QueueView.as_view(), name='queue')
]

project/contests/urls.py
from django.conf.urls import include, url

from . import views, globalviews, settingsviews

contest_urlpatterns = [
    url(r'^$', views.GeneralView.as_view()),
    url(r'^standings/$', views.StandingsView.as_view(wide=False), name='standings'),
    url(r'^standings/wide/$', views.StandingsView.as_view(wide=True), name='standings_wide'),
    url(r'^statements/(?P<filename>.+)$', views.StatementsFileView.as_view(), name='statements'),
    url(r'^problems/$', views.ProblemsView.as_view(), name='problems'),
    url(r'^problems/(?P<problem_id>[0-9]+)/(?P<filename>.+)?$', views.ProblemView.as_view(), name='problem'),
    url(r'^solutions/$', views.AllSolutionsView.as_view(), name='all_solutions'),
    url(r'^my/solutions/$', views.MySolutionsView.as_view(), name='my_solutions'),
    url(r'^submit/$', views.SubmitView.as_view(), name='submit'),
    url(r'^submission/(?P<solution_id>[0-9]+)/$', views.SubmissionView.as_view(), name='submission'),
]

contestsettings_urlpatterns = [
    url(r'^$', settingsviews.PropertiesView.as_view(), name='settings_properties'),
    url(r'^delete/$', settingsviews.DeleteView.as_view(), name='settings_delete'),
    url(r'^compilers/$', settingsviews.CompilersView.as_view(), name='settings_compilers'),
    url(r'^problems/$', settingsviews.ProblemsView.as_view(), name='settings_problems'),
    url(r'^statements/$', settingsviews.StatementsView.as_view(), name='settings_statements'),
    url(r'^problems/list/(?P<folder_id>[0-9]+)/$', settingsviews.ProblemsJsonListView.as_view(), name='settings_problems_json_list'),
    url(r'^users/$', settingsviews.UsersView.as_view(), name='settings_users'),
    url(r'^users/(?P<tag>[a-z]+)/$', settingsviews.UserRoleView.as_view(), name='settings_user_role'),
    url(r'^users/list/(?P<folder_id>[0-9]+)/$', settingsviews.UsersJsonListView.as_view(), name='settings_users_json_list'),
]

urlpatterns = [
    url(r'^$', globalviews.ContestListView.as_view(), name='index'),
    url(r'^new/$', globalviews.ContestCreateView.as_view(), name='new'),

    url(r'^(?P<contest_id>[0-9]+)/', include(contest_urlpatterns)),
    url(r'^(?P<contest_id>[0-9]+)/settings/', include(contestsettings_urlpatterns)),
]

project/irunner2/urls.py
from django.conf.urls import include, url
#from django.contrib import admin
import common.views
from django_js_reverse.views import urls_js
from django.views.decorators.cache import cache_page


urlpatterns = [
    url(r'^$', common.views.home, name='home'),
    url(r'^language/$', common.views.language, name='language'),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
    url(r'^storage/', include('storage.urls', namespace='storage')),
    url(r'^problems/', include('problems.urls', namespace='problems')),
    url(r'^compilers/', include('proglangs.urls', namespace='proglangs')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^', include('solutions.urls', namespace='solutions')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^contests/', include('contests.urls', namespace='contests')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^about/', common.views.about, name='about'),
    url('^', include('cauth.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
    url(r'^hall-of-fame/$', common.views.HallOfFameView.as_view(), name='hall_of_fame')
]

handler403 = 'common.views.error403'

project/problems/urls.py
from django.conf.urls import include, url

from . import views

problem_urlpatterns = [
    url(r'^$', views.ProblemOverviewView.as_view(), name='overview'),
    url(r'^statement/(?P<filename>.+)?$', views.ProblemStatementView.as_view(), name='statement'),

    url(r'^tests/$', views.ProblemTestsView.as_view(), name='tests'),
    url(r'^tests/(?P<test_number>[0-9]+)/$', views.ProblemTestsTestView.as_view(), name='show_test'),
    url(r'^tests/upload/$', views.ProblemTestsUploadArchiveView.as_view(), name='upload_archive'),
    url(r'^tests/new/$', views.ProblemTestsNewView.as_view(), name='new_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/edit/$', views.ProblemTestsTestEditView.as_view(), name='edit_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/delete/$', views.ProblemTestsDeleteView.as_view(), name='delete_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/image/(?P<filename>.+)$', views.ProblemTestsTestImageView.as_view(), name='test_image'),
    url(r'^tests/batch/set/time-limit/$', views.ProblemTestsSetTimeLimitView.as_view(), name='tests_mass_time_limit'),
    url(r'^tests/batch/set/memory-limit/$', views.ProblemTestsSetMemoryLimitView.as_view(), name='tests_mass_memory_limit'),

    url(r'^tests/open/input-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='input', download=False), name='test_input_open'),
    url(r'^tests/download/input-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='input', download=True), name='test_input_download'),
    url(r'^tests/open/answer-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='answer', download=False), name='test_answer_open'),
    url(r'^tests/download/answer-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='answer', download=True), name='test_answer_download'),

    url(r'^solutions/$', views.ProblemSolutionsView.as_view(), name='solutions'),

    url(r'^files/$', views.ProblemFilesView.as_view(), name='files'),
    url(r'^files/data/(?P<file_id>[0-9]+)/open/(?P<filename>.+)$', views.ProblemFilesFileOpenView.as_view(), name='data_file_open'),
    url(r'^files/data/(?P<file_id>[0-9]+)/download/(?P<filename>.+)$', views.ProblemFilesFileOpenView.as_view(download=True), name='data_file_download'),
    url(r'^files/data/(?P<file_id>[0-9]+)/edit/$', views.ProblemFilesDataFileEditView.as_view(), name='data_file_edit'),
    url(r'^files/data/(?P<file_id>[0-9]+)/delete/$', views.ProblemFilesDataFileDeleteView.as_view(), name='data_file_delete'),
    url(r'^files/data/new/$', views.ProblemFilesDataFileNewView.as_view(), name='data_file_new'),

    url(r'^files/source/(?P<file_id>[0-9]+)/open/(?P<filename>.+)$', views.ProblemFilesSourceFileOpenView.as_view(), name='source_file_open'),
    url(r'^files/source/(?P<file_id>[0-9]+)/download/(?P<filename>.+)$', views.ProblemFilesSourceFileOpenView.as_view(download=True), name='source_file_download'),
    url(r'^files/source/(?P<file_id>[0-9]+)/edit/$', views.ProblemFilesSourceFileEditView.as_view(), name='source_file_edit'),
    url(r'^files/source/(?P<file_id>[0-9]+)/delete/$', views.ProblemFilesSourceFileDeleteView.as_view(), name='source_file_delete'),
    url(r'^files/source/new/$', views.ProblemFilesSourceFileNewView.as_view(), name='source_file_new'),

    url(r'^tex/$', views.ProblemTeXView.as_view(), name='tex'),
    url(r'^tex/render/$', views.ProblemTeXRenderView.as_view(), name='tex_render'),
    url(r'^tex/new/statement/$', views.ProblemTeXNewStatementView.as_view(), name='tex_new_statement'),
    url(r'^tex/(?P<file_id>[0-9]+)/$', views.ProblemTeXEditView.as_view(), name='edit_tex'),
    url(r'^tex/(?P<file_id>[0-9]+)/(?P<filename>.+)$', views.ProblemTeXEditRelatedFileView.as_view()),

    url(r'^challenges/$', views.ProblemChallengesView.as_view(), name='challenges'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/$', views.ProblemChallengeView.as_view(), name='challenge'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/status/json/$', views.ProblemChallengeJsonView.as_view(), name='challenge_status_json'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/open/(?P<resource_id>[0-9a-f]*)$', views.ProblemChallengeDataView.as_view(), name='challenge_data'),
    url(r'^challenges/new/$', views.ProblemNewChallengeView.as_view(), name='new_challenge'),

    url(r'^submit/$', views.ProblemSubmitView.as_view(), name='submit'),
    url(r'^submission/(?P<solution_id>[0-9]+)/$', views.ProblemSubmissionView.as_view(), name='submission'),
    url(r'^folders/$', views.ProblemFoldersView.as_view(), name='folders'),
    url(r'^properties/$', views.ProblemPropertiesView.as_view(), name='properties'),
    url(r'^pictures/$', views.ProblemPicturesView.as_view(), name='pictures'),
    url(r'^validator/$', views.ProblemValidatorView.as_view(), name='validator'),
]

urlpatterns = [
    url(r'^tree/$', views.ShowTreeView.as_view(), name='show_tree'),
    url(r'^tree/(?P<folder_id>[0-9]+)/$', views.ShowTreeFolderView.as_view(), name='show_tree_folder'),
    url(r'^tree/(?P<folder_id>[0-9]+)/json/$', views.ShowTreeFolderJsonView.as_view(), name='show_tree_folder_json'),

    url(r'^(?P<problem_id>[0-9]+)/', include(problem_urlpatterns)),

    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/$', views.ShowFolderView.as_view(), name='show_folder'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/new/folder/$', views.CreateFolderView.as_view(), name='create_folder'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/properties/$', views.UpdateFolderView.as_view(), name='folder_properties'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/delete/$', views.DeleteFolderView.as_view(), name='delete_folder'),

    url(r'^search/$', views.SearchView.as_view(), name='search'),

    url(r'^tex/$', views.TeXView.as_view(), name='tex_playground'),
    url(r'^tex/render/$', views.TeXRenderView.as_view(), name='tex_playground_render'),
]

project/solutions/urls.py
from django.conf.urls import include, url

from . import views

solutions_urlpatterns = [
    url(r'^$', views.SolutionListView.as_view(), name='list'),

    url(r'^(?P<solution_id>[0-9]+)/$', views.SolutionMainView.as_view(), name='main'),
    url(r'^(?P<solution_id>[0-9]+)/source/$', views.SolutionSourceView.as_view(), name='source'),
    url(r'^(?P<solution_id>[0-9]+)/log/$', views.SolutionLogView.as_view(), name='log'),
    url(r'^(?P<solution_id>[0-9]+)/tests/$', views.SolutionTestsView.as_view(), name='tests'),
    url(r'^(?P<solution_id>[0-9]+)/runs/$', views.SolutionJudgementsView.as_view(), name='judgements'),
    url(r'^(?P<solution_id>[0-9]+)/attempts/$', views.SolutionAttemptsView.as_view(), name='attempts'),
    url(r'^(?P<solution_id>[0-9]+)/status/json/$', views.SolutionStatusJsonView.as_view(), name='status_json'),

    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/$', views.SolutionTestCaseResultView.as_view(), name='test_case_result'),
    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/(?P<mode>input|output|answer|stdout|stderr)\.txt$', views.SolutionTestCaseResultDataView.as_view(), name='test_data'),
    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/images/(?P<filename>.*)$', views.SolutionTestCaseResultImageView.as_view(), name='test_image'),

    url(r'^(?P<solution_id>[0-9]+)/source/open/(?P<filename>.*)$', views.SolutionSourceOpenView.as_view(), name='source_open'),
    url(r'^(?P<solution_id>[0-9]+)/source/download/(?P<filename>.*)$', views.SolutionSourceDownloadView.as_view(), name='source_download'),

    url(r'^delete/$', views.DeleteSolutionsView.as_view(), name='delete'),

    url(r'^compare/$', views.CompareSolutionsView.as_view(), name='compare'),
]

judgements_urlpatterns = [
    url(r'^$', views.JudgementListView.as_view(), name='judgement_list'),
    url(r'^(?P<judgement_id>[0-9]+)/$', views.JudgementView.as_view(), name='show_judgement'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/$', views.JudgementTestCaseResultView.as_view(), name='judgement_testcaseresult'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/(?P<mode>input|output|answer|stdout|stderr)\.txt$', views.JudgementTestCaseResultDataView.as_view(), name='judgement_testdata'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/images/(?P<filename>.*)$', views.JudgementTestCaseResultImageView.as_view(), name='judgement_testimage'),
]

rejudges_urlpatterns = [
    url(r'^new/$', views.CreateRejudgeView.as_view(), name='create_rejudge'),
    url(r'^(?P<rejudge_id>[0-9]+)/$', views.RejudgeView.as_view(), name='rejudge'),
    url(r'^(?P<rejudge_id>[0-9]+)/status/json/$', views.RejudgeJsonView.as_view(), name='rejudge_status_json'),
    url(r'^$', views.RejudgeListView.as_view(), name='rejudge_list'),
]

urlpatterns = [
    url(r'^solutions/', include(solutions_urlpatterns)),
    url(r'^runs/', include(judgements_urlpatterns)),
    url(r'^rejudges/', include(rejudges_urlpatterns)),
]

project/contests/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib import auth
from django.utils.translation import ugettext_lazy as _

from common.fields import TwoPanelModelMultipleChoiceField
from problems.models import Problem, ProblemFolder
from solutions.forms import SolutionForm
from users.models import UserFolder

from .models import Contest


class PropertiesForm(forms.ModelForm):
    class Meta:
        model = Contest
        fields = ['name', 'start_time', 'duration', 'freeze_time', 'show_pending_runs', 'unfreeze_standings', 'enable_upsolving',
                  'unauthorized_access', 'contestant_own_solutions_access', 'attempt_limit', 'file_size_limit']
        help_texts = {
            'contestant_own_solutions_access': _('Each access level includes all the previous onces.')
        }


class CompilersForm(forms.ModelForm):
    class Meta:
        model = Contest
        fields = ['compilers']
        labels = {
            'compilers': ''
        }
        widgets = {
            'compilers': forms.CheckboxSelectMultiple
        }


class TwoPanelProblemMultipleChoiceField(TwoPanelModelMultipleChoiceField):
    @classmethod
    def label_from_instance(cls, obj):
        return obj.numbered_full_name()


class ProblemsForm(forms.Form):
    problems = TwoPanelProblemMultipleChoiceField(label=_('Problems'), required=False,
                                                  help_text=_('Order of problem addition is significant.'),
                                                  model=Problem, folder_model=ProblemFolder, clean_to_list=True,
                                                  url_pattern='contests:settings_problems_json_list')


class StatementsForm(forms.Form):
    upload = forms.FileField(label=_('Statements file'), required=False,
                             help_text=_('You can upload a single file containing statements of all problems (usually in PDF format).'))


class TwoPanelUserMultipleChoiceField(TwoPanelModelMultipleChoiceField):
    @classmethod
    def label_from_instance(cls, obj):
        return obj.get_full_name()


class UsersForm(forms.Form):
    users = TwoPanelUserMultipleChoiceField(label=_('Users'), required=False,
                                            model=auth.get_user_model(), folder_model=UserFolder,
                                            url_pattern='contests:settings_users_json_list')


class SolutionListUserForm(forms.Form):
    def __init__(self, *args, **kwargs):
        user_choices = kwargs.pop('user_choices')
        super(SolutionListUserForm, self).__init__(*args, **kwargs)
        self.fields['user'] = forms.TypedChoiceField(label=_('User'), choices=user_choices, coerce=int, empty_value=None, required=True)
        self.fields['user'].widget.attrs['class'] = 'form-control'


class SolutionListProblemForm(forms.Form):
    def __init__(self, *args, **kwargs):
        problem_choices = kwargs.pop('problem_choices')
        super(SolutionListProblemForm, self).__init__(**kwargs)
        self.fields['problem'] = forms.TypedChoiceField(label=_('Problem'), choices=problem_choices, coerce=int, empty_value=None, required=True)
        self.fields['problem'].widget.attrs['class'] = 'form-control'


class ContestSolutionForm(SolutionForm):
    def __init__(self, problem_choices, compiler_queryset, **kwargs):
        super(ContestSolutionForm, self).__init__(**kwargs)
        self.fields['problem'] = forms.TypedChoiceField(label=_('Problem'), choices=problem_choices, coerce=int)
        self.fields['compiler'].queryset = compiler_queryset

project/contests/templates/contests/all_solutions.html
{% extends 'contests/base.html' %}

{% load i18n %}
{% load irunner_contests %}
{% load irunner_proglangs %}
{% load irunner_solutions %}
{% load irunner_pagination %}
{% load irunner_users %}
{% load bootstrap3 %}

{% block subtitle %}{% trans 'All solutions' %}{% endblock %}

{% block main %}
    <form method="get" class="form-inline">
        <div class="ir-solution-filter">
            {{ problem_form.problem }}
            {{ user_form.user }}
            <button type="submit" class="btn btn-default">
                {% trans 'Apply' %}
            </button>
        </div>
    </form>

    {% if object_list %}
        {% irunner_pagination pagination_context %}
        <table class="table table-condensed table-striped ir-compact-table">
            <thead>
                <tr>
                    <th>{% trans 'Problem' %}</th>
                    <th>{% trans 'Author' %}</th>
                    <th>{% trans 'Time' %}</th>
                    <th>{% trans 'File' %}</th>
                    <th>{% trans 'Status' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for solution in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'contests:problem' contest.id solution.problem_id %}">{% irunner_contests_showproblem resolver solution.problem_id %}</a>
                    </td>
                    <td>{% irunner_users_show solution.author %}</td>
                    <td>{{ solution.reception_time }}</td>
                    <td>
                        {% irunner_proglangs_compilerbox solution.compiler tooltip=True %}
                        <a href="{% url 'solutions:source' solution.id %}" class="ir-monospace">{{ solution.source_code.filename }}</a>
                        <span class="ir-file-size">({{ solution.source_code.size|filesizeformat }})</span>
                    </td>
                    <td>
                        <a href="{% url 'solutions:main' solution.id %}">{% irunner_solutions_judgementbox solution.best_judgement tooltip=True %}</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="ir-absence">
            {% trans 'No solutions' %}
        </div>
    {% endif %}
{% endblock %}

project/contests/templates/contests/base.html
{% extends 'base.html' %}

{% block title %}{% block subtitle %}{% endblock %} &mdash; {{ contest }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3">
        {% include 'contests/sidebar.html' %}

        {% block extrasidebar %}
        {% endblock %}
    </div>
    <div class="col-md-9">
        {% block main %}
        {% endblock %}
    </div>
</div>
{% endblock %}

project/contests/templates/contests/my_solutions.html
{% extends 'contests/base.html' %}

{% load i18n %}
{% load irunner_contests %}
{% load irunner_proglangs %}
{% load irunner_solutions %}
{% load irunner_pagination %}
{% load irunner_users %}
{% load bootstrap3 %}

{% block subtitle %}{% trans 'All solutions' %}{% endblock %}

{% block main %}
    <form method="get" class="form-inline">
        <div class="ir-solution-filter">
            {{ problem_form.problem }}
            {{ user_form.user }}
            <button type="submit" class="btn btn-default">
                {% trans 'Apply' %}
            </button>
        </div>
    </form>

    {% if object_list %}
        {% irunner_pagination pagination_context %}
        <table class="table table-condensed table-striped ir-compact-table">
            <thead>
                <tr>
                    <th>{% trans '#' %}</th>
                    <th>{% trans 'Problem' %}</th>
                    <th>{% trans 'Time' %}</th>
                    <th>{% trans 'File' %}</th>
                    <th>{% trans 'Status' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for solution in object_list %}
                <tr>
                    <td>{{ forloop.revcounter }}</td>
                    <td>
                        <a href="{% url 'contests:problem' contest.id solution.problem_id %}">{% irunner_contests_showproblem resolver solution.problem_id %}</a>
                    </td>
                    <td>{{ solution.reception_time }}</td>
                    <td>
                        {% irunner_proglangs_compilerbox solution.compiler tooltip=True %}
                        <a href="{% url 'solutions:source' solution.id %}" class="ir-monospace">{{ solution.source_code.filename }}</a>
                        <span class="ir-file-size">({{ solution.source_code.size|filesizeformat }})</span>
                    </td>
                    <td>
                        {% irunner_solutions_judgementbox solution.best_judgement tooltip=False %}
                        {% if solution.best_judgement %}
                            <a href="{% url 'solutions:main' solution.id %}">{{ solution.best_judgement.show_status }}</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="ir-absence">
            {% trans 'No solutions' %}
        </div>
    {% endif %}
{% endblock %}

project/contests/templates/contests/problem.html
{% extends 'contests/base.html' %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_problems %}

{% block subtitle %}{% trans 'Problem' %} {{ problem.numbered_full_name }}{% endblock %}

{% block extrasidebar %}
    {% if user.is_staff %}
        <ul class="list-group">
            <a href="{% url 'problems:overview' problem.id %}" class="list-group-item" target="_blank">
                {% bootstrap_icon 'pencil' %} <span class="ir-icon-label">{% trans 'Edit' %}</span>
            </a>
        </ul>
    {% endif %}
{% endblock %}

{% block main %}
    {% irunner_problems_statement statement %}
{% endblock %}

project/contests/templates/contests/settings_users.html
{% extends 'contests/settings_base.html' %}

{% load i18n %}
{% load irunner_users %}
{% load bootstrap3 %}

{% block submain %}
    {% bootstrap_messages %}

    {% for view_model in view_models %}
        {# view_model is RoleUsersViewModel #}
        <div class="pull-right">
            <a href="{% url 'contests:settings_user_role' contest.id view_model.tag %}" class="btn btn-sm btn-default">
                {% bootstrap_icon 'pencil' %} <span class="ir-icon-label">{% trans 'Edit the list' %}</span>
            </a>
        </div>
        <h3>{{ view_model.name_plural }}</h3>
        {% if view_model.users %}
            <ol>
                {% for user in view_model.users %}
                    <li><a href="{% url 'users:profile_show' user.id %}">{% irunner_users_show user %}</a></li>
                {% endfor %}
            </ol>
        {% else %}
            <div class="ir-absence">{% trans 'No users are set' %}</div>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
{% endblock %}

project/contests/templates/contests/settings_users_edit.html
{% extends 'contests/settings_base.html' %}

{% load bootstrap3 %}
{% load i18n %}

{% block submain %}
    <h3>{{ name_plural }}</h3>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% trans 'Save' %}
            </button>
            <a href="{% url 'contests:settings_users' contest.id %}" class="btn btn-default">
                {% trans 'Cancel' %}
            </a>
        {% endbuttons %}
    </form>
{% endblock %}

project/contests/templates/contests/sidebar.html
{% load bootstrap3 %}
{% load i18n %}

<ul class="list-group ir-list-group-success">
    <li class="list-group-item list-group-item-success{% if active_tab == 'info' %} active{% endif %}">
        {% bootstrap_icon 'info-sign' %}
        <span class="ir-icon-label">{{ contest.name }}</span>
    </li>

    {% if permissions.problems %}
        <a href="{% url 'contests:problems' contest.id %}" class="list-group-item{% if active_tab == 'problems' %} active{% endif %}">
            {% bootstrap_icon 'briefcase' %}
            <span class="ir-icon-label">{% trans 'Problems' %}</span>
        </a>
    {% endif %}

    {% if permissions.standings %}
        <a href="{% url 'contests:standings' contest.id %}" class="list-group-item{% if active_tab == 'standings' %} active{% endif %}">
            {% bootstrap_icon 'list-alt' %}
            <span class="ir-icon-label">{% trans 'Standings' context 'contest' %}</span>
        </a>
    {% endif %}

    {% if permissions.all_solutions %}
        <a href="{% url 'contests:all_solutions' contest.id %}" class="list-group-item{% if active_tab == 'all_solutions' %} active{% endif %}">
            {% bootstrap_icon 'tasks' %}
            <span class="ir-icon-label">{% trans 'All solutions' %}</span>
        </a>
    {% endif %}

    {% if permissions.my_solutions %}
        <a href="{% url 'contests:my_solutions' contest.id %}" class="list-group-item{% if active_tab == 'my_solutions' %} active{% endif %}">
            {% bootstrap_icon 'tasks' %}
            <span class="ir-icon-label">{% trans 'My solutions' %}</span>
        </a>
    {% endif %}

    {% if permissions.submit %}
        <a href="{% url 'contests:submit' contest.id %}{% if problem_to_submit %}?problem={{ problem_to_submit }}{% endif %}" class="list-group-item{% if active_tab == 'submit' %} active{% endif %}">
            {% bootstrap_icon 'send' %}
            <span class="ir-icon-label">{% if problem_to_submit %}<strong>{% endif %}{% trans 'Submit solution' %}{% if problem_to_submit %}</strong>{% endif %}</span>
        </a>
    {% endif %}

    {% if permissions.settings %}
        <a href="{% url 'contests:settings_properties' contest.id %}" class="list-group-item{% if active_tab == 'settings' %} active{% endif %}">
            {% bootstrap_icon 'cog' %}
            <span class="ir-icon-label">{% trans 'Settings' %}</span>
        </a>
    {% endif %}
</ul>