project/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^fs/status$', views.FileStatusView.as_view(), name='fs_status'),
    url(r'^fs/(?P<filename>[0-9a-f]*)$', views.FileView.as_view(), name='fs_status'),
    url(r'^jobs/take$', views.JobTakeView.as_view(), name='take_job'),
    url(r'^jobs/(?P<job_id>\d+)/result$', views.JobPutResultView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/state$', views.JobPutStateView.as_view()),

    url(r'^queue/$', views.QueueView.as_view(), name='queue')
]

project/irunner2/urls.py
from django.conf.urls import include, url
#from django.contrib import admin
import common.views
from django_js_reverse.views import urls_js
from django.views.decorators.cache import cache_page


urlpatterns = [
    url(r'^$', common.views.home, name='home'),
    url(r'^language/$', common.views.language, name='language'),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
    url(r'^storage/', include('storage.urls', namespace='storage')),
    url(r'^problems/', include('problems.urls', namespace='problems')),
    url(r'^compilers/', include('proglangs.urls', namespace='proglangs')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^', include('solutions.urls', namespace='solutions')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^contests/', include('contests.urls', namespace='contests')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^about/', common.views.about, name='about'),
    url('^', include('cauth.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
    url(r'^hall-of-fame/$', common.views.HallOfFameView.as_view(), name='hall_of_fame')
]

handler403 = 'common.views.error403'

project/problems/urls.py
from django.conf.urls import include, url

from . import views

problem_urlpatterns = [
    url(r'^$', views.ProblemOverviewView.as_view(), name='overview'),
    url(r'^statement/(?P<filename>.+)?$', views.ProblemStatementView.as_view(), name='statement'),

    url(r'^tests/$', views.ProblemTestsView.as_view(), name='tests'),
    url(r'^tests/(?P<test_number>[0-9]+)/$', views.ProblemTestsTestView.as_view(), name='show_test'),
    url(r'^tests/upload/$', views.ProblemTestsUploadArchiveView.as_view(), name='upload_archive'),
    url(r'^tests/new/$', views.ProblemTestsNewView.as_view(), name='new_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/edit/$', views.ProblemTestsTestEditView.as_view(), name='edit_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/delete/$', views.ProblemTestsDeleteView.as_view(), name='delete_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/image/(?P<filename>.+)$', views.ProblemTestsTestImageView.as_view(), name='test_image'),
    url(r'^tests/batch/set/time-limit/$', views.ProblemTestsSetTimeLimitView.as_view(), name='tests_mass_time_limit'),
    url(r'^tests/batch/set/memory-limit/$', views.ProblemTestsSetMemoryLimitView.as_view(), name='tests_mass_memory_limit'),

    url(r'^tests/open/input-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='input', download=False), name='test_input_open'),
    url(r'^tests/download/input-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='input', download=True), name='test_input_download'),
    url(r'^tests/open/answer-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='answer', download=False), name='test_answer_open'),
    url(r'^tests/download/answer-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='answer', download=True), name='test_answer_download'),

    url(r'^solutions/$', views.ProblemSolutionsView.as_view(), name='solutions'),

    url(r'^files/$', views.ProblemFilesView.as_view(), name='files'),
    url(r'^files/data/(?P<file_id>[0-9]+)/open/(?P<filename>.+)$', views.ProblemFilesFileOpenView.as_view(), name='data_file_open'),
    url(r'^files/data/(?P<file_id>[0-9]+)/download/(?P<filename>.+)$', views.ProblemFilesFileOpenView.as_view(download=True), name='data_file_download'),
    url(r'^files/data/(?P<file_id>[0-9]+)/edit/$', views.ProblemFilesDataFileEditView.as_view(), name='data_file_edit'),
    url(r'^files/data/(?P<file_id>[0-9]+)/delete/$', views.ProblemFilesDataFileDeleteView.as_view(), name='data_file_delete'),
    url(r'^files/data/new/$', views.ProblemFilesDataFileNewView.as_view(), name='data_file_new'),

    url(r'^files/source/(?P<file_id>[0-9]+)/open/(?P<filename>.+)$', views.ProblemFilesSourceFileOpenView.as_view(), name='source_file_open'),
    url(r'^files/source/(?P<file_id>[0-9]+)/download/(?P<filename>.+)$', views.ProblemFilesSourceFileOpenView.as_view(download=True), name='source_file_download'),
    url(r'^files/source/(?P<file_id>[0-9]+)/edit/$', views.ProblemFilesSourceFileEditView.as_view(), name='source_file_edit'),
    url(r'^files/source/(?P<file_id>[0-9]+)/delete/$', views.ProblemFilesSourceFileDeleteView.as_view(), name='source_file_delete'),
    url(r'^files/source/new/$', views.ProblemFilesSourceFileNewView.as_view(), name='source_file_new'),

    url(r'^tex/$', views.ProblemTeXView.as_view(), name='tex'),
    url(r'^tex/render/$', views.ProblemTeXRenderView.as_view(), name='tex_render'),
    url(r'^tex/new/statement/$', views.ProblemTeXNewStatementView.as_view(), name='tex_new_statement'),
    url(r'^tex/(?P<file_id>[0-9]+)/$', views.ProblemTeXEditView.as_view(), name='edit_tex'),
    url(r'^tex/(?P<file_id>[0-9]+)/(?P<filename>.+)$', views.ProblemTeXEditRelatedFileView.as_view()),

    url(r'^challenges/$', views.ProblemChallengesView.as_view(), name='challenges'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/$', views.ProblemChallengeView.as_view(), name='challenge'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/status/json/$', views.ProblemChallengeJsonView.as_view(), name='challenge_status_json'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/open/(?P<resource_id>[0-9a-f]*)$', views.ProblemChallengeDataView.as_view(), name='challenge_data'),
    url(r'^challenges/new/$', views.ProblemNewChallengeView.as_view(), name='new_challenge'),

    url(r'^submit/$', views.ProblemSubmitView.as_view(), name='submit'),
    url(r'^submission/(?P<solution_id>[0-9]+)/$', views.ProblemSubmissionView.as_view(), name='submission'),
    url(r'^folders/$', views.ProblemFoldersView.as_view(), name='folders'),
    url(r'^properties/$', views.ProblemPropertiesView.as_view(), name='properties'),
    url(r'^pictures/$', views.ProblemPicturesView.as_view(), name='pictures'),
    url(r'^validator/$', views.ProblemValidatorView.as_view(), name='validator'),
]

urlpatterns = [
    url(r'^tree/$', views.ShowTreeView.as_view(), name='show_tree'),
    url(r'^tree/(?P<folder_id>[0-9]+)/$', views.ShowTreeFolderView.as_view(), name='show_tree_folder'),
    url(r'^tree/(?P<folder_id>[0-9]+)/json/$', views.ShowTreeFolderJsonView.as_view(), name='show_tree_folder_json'),

    url(r'^(?P<problem_id>[0-9]+)/', include(problem_urlpatterns)),

    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/$', views.ShowFolderView.as_view(), name='show_folder'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/new/folder/$', views.CreateFolderView.as_view(), name='create_folder'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/properties/$', views.UpdateFolderView.as_view(), name='folder_properties'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/delete/$', views.DeleteFolderView.as_view(), name='delete_folder'),

    url(r'^search/$', views.SearchView.as_view(), name='search'),

    url(r'^tex/$', views.TeXView.as_view(), name='tex_playground'),
    url(r'^tex/render/$', views.TeXRenderView.as_view(), name='tex_playground_render'),
]

project/solutions/urls.py
from django.conf.urls import include, url

from . import views

solutions_urlpatterns = [
    url(r'^$', views.SolutionListView.as_view(), name='list'),

    url(r'^(?P<solution_id>[0-9]+)/$', views.SolutionMainView.as_view(), name='main'),
    url(r'^(?P<solution_id>[0-9]+)/source/$', views.SolutionSourceView.as_view(), name='source'),
    url(r'^(?P<solution_id>[0-9]+)/log/$', views.SolutionLogView.as_view(), name='log'),
    url(r'^(?P<solution_id>[0-9]+)/tests/$', views.SolutionTestsView.as_view(), name='tests'),
    url(r'^(?P<solution_id>[0-9]+)/runs/$', views.SolutionJudgementsView.as_view(), name='judgements'),
    url(r'^(?P<solution_id>[0-9]+)/attempts/$', views.SolutionAttemptsView.as_view(), name='attempts'),
    url(r'^(?P<solution_id>[0-9]+)/status/json/$', views.SolutionStatusJsonView.as_view(), name='status_json'),

    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/$', views.SolutionTestCaseResultView.as_view(), name='test_case_result'),
    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/(?P<mode>input|output|answer|stdout|stderr)\.txt$', views.SolutionTestCaseResultDataView.as_view(), name='test_data'),
    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/images/(?P<filename>.*)$', views.SolutionTestCaseResultImageView.as_view(), name='test_image'),

    url(r'^(?P<solution_id>[0-9]+)/source/open/(?P<filename>.*)$', views.SolutionSourceOpenView.as_view(), name='source_open'),
    url(r'^(?P<solution_id>[0-9]+)/source/download/(?P<filename>.*)$', views.SolutionSourceDownloadView.as_view(), name='source_download'),

    url(r'^delete/$', views.DeleteSolutionsView.as_view(), name='delete'),

    url(r'^compare/$', views.CompareSolutionsView.as_view(), name='compare'),
]

judgements_urlpatterns = [
    url(r'^$', views.JudgementListView.as_view(), name='judgement_list'),
    url(r'^(?P<judgement_id>[0-9]+)/$', views.JudgementView.as_view(), name='show_judgement'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/$', views.JudgementTestCaseResultView.as_view(), name='judgement_testcaseresult'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/(?P<mode>input|output|answer|stdout|stderr)\.txt$', views.JudgementTestCaseResultDataView.as_view(), name='judgement_testdata'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/images/(?P<filename>.*)$', views.JudgementTestCaseResultImageView.as_view(), name='judgement_testimage'),
]

rejudges_urlpatterns = [
    url(r'^new/$', views.CreateRejudgeView.as_view(), name='create_rejudge'),
    url(r'^(?P<rejudge_id>[0-9]+)/$', views.RejudgeView.as_view(), name='rejudge'),
    url(r'^(?P<rejudge_id>[0-9]+)/status/json/$', views.RejudgeJsonView.as_view(), name='rejudge_status_json'),
    url(r'^$', views.RejudgeListView.as_view(), name='rejudge_list'),
]

urlpatterns = [
    url(r'^solutions/', include(solutions_urlpatterns)),
    url(r'^runs/', include(judgements_urlpatterns)),
    url(r'^rejudges/', include(rejudges_urlpatterns)),
]

project/solutions/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _

from common.constants import EMPTY_SELECT, make_empty_select
from proglangs.models import Compiler
from proglangs.utils import guess_filename
from storage.validators import validate_filename


class AdHocForm(forms.Form):
    source_code = forms.CharField(widget=forms.Textarea)
    input_data = forms.CharField(widget=forms.Textarea)
    compiler = forms.ModelChoiceField(queryset=Compiler.objects.all().order_by('description'))


class SolutionForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.file_size_limit = kwargs.pop('file_size_limit', None)
        super(SolutionForm, self).__init__(*args, **kwargs)

    compiler = forms.ModelChoiceField(
        label=_('Compiler'),
        required=True,
        queryset=Compiler.objects.all().order_by('description'),
        empty_label=EMPTY_SELECT,
    )
    text = forms.CharField(
        label=_('Enter source code'),
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control ir-monospace'}),
        max_length=2**20
    )
    upload = forms.FileField(
        label=_(u'…or upload a file'),
        required=False,
        widget=forms.FileInput,
        max_length=255,
        help_text=_('If you select a file, text field content is ignored.')
    )

    def _check_size(self, text, upload):
        if self.file_size_limit is None:
            return

        size = 0
        if upload is not None:
            size = upload.size
        elif text is not None:
            size = len(text.encode('utf-8'))

        if size > self.file_size_limit:
            raise forms.ValidationError(
                _('The size of the source file (%(actual)d B) exceeds the limit (%(limit)d B).'),
                code='too_big',
                params={'actual': size, 'limit': self.file_size_limit},
            )

    def clean(self):
        cleaned_data = super(SolutionForm, self).clean()
        text = cleaned_data.get('text')
        upload = cleaned_data.get('upload')
        compiler = cleaned_data.get('compiler')

        if (upload is None) and (text is not None) and (len(text) == 0):
            raise forms.ValidationError(_('Unable to submit an empty solution.'), code='empty')

        filename = None
        if upload is not None:
            filename = upload.name
        else:
            # need to guess filename
            if compiler is not None and text is not None:
                filename = guess_filename(compiler.language, text)

        if filename is None:
            raise forms.ValidationError(_('Unable to determine the name of the source file. '
                                          'For Java code, make sure you have a single public class defined. '
                                          'You can also try to upload a file instead of using direct input of code.'), code='no_name')

        validate_filename(filename)
        cleaned_data['filename'] = filename

        self._check_size(text, upload)


class AllSolutionsFilterForm(forms.Form):
    STATE_CHOICES = (
        ('', make_empty_select(_('status'))),
        (_('state'), (
            ('waiting', _('Waiting')),
            ('preparing', _('Preparing')),
            ('compiling', _('Compiling')),
            ('testing', _('Testing')),
            ('finishing', _('Finishing')),
            ('done', _('Done')),
            ('not-done', _('Not Done')),
        )),
        (_('outcome'), (
            ('ok', _('Accepted')),
            ('ce', _('Compilation Error')),
            ('wa', _('Wrong Answer')),
            ('tle', _('Time Limit Exceeded')),
            ('mle', _('Memory Limit Exceeded')),
            ('ile', _('Idleness Limit Exceeded')),
            ('rte', _('Run-time Error')),
            ('pe', _('Presentation Error')),
            ('sv', _('Security Violation')),
            ('cf', _('Check Failed'))
        )),
    )
    state = forms.ChoiceField(choices=STATE_CHOICES, required=False)

    DEFAULT_COMPILER_CHOICES = (
        ('', make_empty_select(_('language'))),
        (_('language'), Compiler.LANGUAGE_CHOICES[1:]),
    )
    compiler = forms.ChoiceField(choices=DEFAULT_COMPILER_CHOICES, required=False)

    problem = forms.IntegerField(label=_('Problem ID'), required=False, widget=forms.TextInput)
    user = forms.IntegerField(label=_('User ID'), required=False, widget=forms.TextInput)

    def __init__(self, *args, **kwargs):
        super(AllSolutionsFilterForm, self).__init__(*args, **kwargs)

        present_compiler_choices = ((_('compiler'), tuple(
            (unicode(compiler.id), unicode(compiler))
            for compiler in Compiler.objects.all()
        )), )

        self.fields['compiler'].choices = self.DEFAULT_COMPILER_CHOICES + present_compiler_choices


class CompareSolutionsForm(forms.Form):
    first = forms.IntegerField(min_value=0, label=_('First solution'), required=True)
    second = forms.IntegerField(min_value=0, label=_('Second solution'), required=True)
    diff = forms.BooleanField(label=_('Show only contextual differences, else show full files'), required=False)

project/solutions/templates/solutions/irunner_solutions_rejudgestate_tag.html
{% load i18n %}

{% if committed == True %}
    <span class="text-success">{% trans 'committed' %}</span>
{% elif committed == False %}
    <span class="text-danger">{% trans 'rolled back' %}</span>
{% else %}
    &mdash;
{% endif %}

project/solutions/templates/solutions/irunner_solutions_scorebox_tag.html
<div class="ir-box ir-scorebox{% if accepted %} ir-scorebox-accepted{% endif %}">{% if defined %}{{ score }}{% if score != max_score %}&thinsp;/&thinsp;{{ max_score }}{% endif %}{% else %}&mdash;{% endif %}</div>

project/solutions/templates/solutions/irunner_solutions_sourcelink_tag.html
{% load bootstrap3 %}
{% load irunner_proglangs %}
{% load i18n %}

{% irunner_proglangs_compilerbox solution.compiler tooltip=True %}
<span class="ir-icons"><!--
--><a href="{% url 'solutions:source' solution.id %}" title="{% trans 'View source code' %}">{% bootstrap_icon 'folder-open' %}</a><!--
--><a href="{% url 'solutions:source_download' solution.id solution.source_code.filename %}" title="{% trans 'Download' %} {{ solution.source_code.filename }}">{% bootstrap_icon 'cloud-download' %}</a><!--
--></span>
<span class="ir-file-size">({{ solution.source_code.size|filesizeformat }})</span>

project/solutions/templates/solutions/rejudge.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_problems %}
{% load irunner_proglangs %}
{% load irunner_progress %}
{% load irunner_solutions %}
{% load irunner_users %}

{% block content %}
    <h2>{% block title %}{% trans 'Rejudge' %} {{ rejudge.id }}{% endblock %}</h2>

    <dl class="dl-horizontal">
        <dt>{% trans 'Created' %}</dt>
        <dd>{{ rejudge.creation_time }}</dd>

        <dt>{% trans 'Author' %}</dt>
        <dd>{% irunner_users_show rejudge.author %}</dd>

        {% if problem %}
            <dt>{% trans 'Problem' %}</dt>
            <dd>{% irunner_problems_difficulty problem.difficulty %} <a href="{% url 'problems:statement' problem.id %}">{{ problem.numbered_full_name }}</a></dd>
        {% endif %}

        <dt>{% trans 'State' %}</dt>
        <dd>{% irunner_solutions_rejudgestate rejudge.committed %}</dd>

        <dt>{% trans 'Result' %}</dt>
        <dd>{% irunner_progress url=progress_url value_good=stats.accepted value_bad=stats.rejected total=stats.total %}</dd>
    </dl>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th>{% trans '#' %}</th>
                <th>ID</th>
                <th>{% trans 'Submission time' %}</th>
                <th>{% trans 'Solution' %}</th>
                <th>{% trans 'Author' %}</th>
                <th>{% trans 'Current' %}</th>
                <th>{% trans 'After Rejudge' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for info in object_list %}
            <tr>
                <td>
                    {{ forloop.counter }}
                </td>
                <td>
                    <a href="{% url 'solutions:main' info.solution.id %}">{{ info.solution.id }}</a>
                </td>
                <td>
                    {{ info.solution.reception_time }}
                </td>
                <td>
                    {% url 'solutions:source' info.solution.id as source_url %}
                    {% irunner_proglangs_compilerbox info.solution.compiler tooltip=True %}
                    <small><tt><a href="{{ source_url }}">{{ info.solution.source_code.filename }}</a></tt></small>
                </td>
                <td>
                    {% irunner_users_show info.solution.author %}
                </td>
                <td>
                    {% if info.before %}
                        <a href="{% url 'solutions:show_judgement' info.before.id %}">
                            {% irunner_solutions_judgementbox info.before tooltip=True %}{% irunner_solutions_scorebox info.before %}
                        </a>
                    {% endif %}
                </td>
                <td>
                    {% if info.after %}
                        <a href="{% url 'solutions:show_judgement' info.after.id %}">
                            {% irunner_solutions_judgementbox info.after tooltip=True %}{% irunner_solutions_scorebox info.after %}
                        </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if rejudge.committed == None %}
        <form method="post">
            {% csrf_token %}
            {% buttons %}
                <button type="submit" name="commit" class="btn btn-primary">{% trans 'Commit' %}</button>
                <button type="submit" name="rollback" class="btn btn-default">{% trans 'Rollback' %}</button>
            {% endbuttons %}
        </form>
    {% endif %}

    <p>
        <a href="{% url 'solutions:rejudge_list' %}">{% trans 'To the list of rejudges' %}</a>
    </p>
{% endblock %}

project/solutions/templates/solutions/solution.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_solutions %}
{% load irunner_problems %}
{% load irunner_proglangs %}
{% load irunner_users %}
{% load staticfiles %}

{% block title %}{% block subtitle %}{% endblock %} &mdash; {% trans 'Solution' %} {{ solution.id }}{% endblock %}

{% block content %}
<div class="panel panel-default ir-solution-panel">
    <div class="panel-body">
        <h2>
            {% irunner_solutions_judgementbox solution.best_judgement tooltip=True %}
            {% trans 'Solution' %} {{ solution.id }}
        </h2>
        <div class="row">
            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>{% trans 'Author' %}</dt>
                    {% if solution_environment.course %}
                        <dd>
                            <a href="{% if solution.author == user %}{% url 'courses:my_solutions' solution_environment.course.id %}{% else %}{% url 'courses:all_solutions' solution_environment.course.id %}?user={{ solution.author.id }}{% endif %}">
                                {% irunner_users_show solution.author %}
                            </a>
                        </dd>
                    {% else %}
                        <dd>{% irunner_users_show solution.author %}</dd>
                    {% endif %}

                    {% if solution.problem %}
                        <dt>{% trans 'Problem' %}</dt>
                        {# What link to the problem is the best? #}
                        <dd>
                            {% irunner_problems_difficulty solution.problem.difficulty %}
                            {% if user.is_staff %}
                                <a href="{% url 'problems:statement' solution.problem_id %}">{{ solution.problem.numbered_full_name }}</a>
                            {% elif solution_environment.course %}
                                <a href="{% url 'courses:course_problems_problem' solution_environment.course.id solution.problem_id %}">{{ solution.problem.numbered_full_name }}</a>
                            {% else %}
                                {# no link, just name #}
                                {{ solution.problem.numbered_full_name }}
                            {% endif %}
                        </dd>

                        <dt>{% trans 'Input&thinsp;/&thinsp;output' %}</dt>
                        <dd>{% irunner_problems_inputfile solution.problem.input_filename %}&thinsp;/&thinsp;{% irunner_problems_outputfile solution.problem.output_filename %}</dd>
                    {% endif %}

                    {% if solution_environment.course %}
                        <dt>{% trans 'Course' %}</dt>
                        <dd><a href="{% url 'courses:show_course_info' solution_environment.course.id %}">{{ solution_environment.course }}</a></dd>

                        {% if solution.best_judgement %}
                            <dt>{% trans 'Score' %}</dt>
                            <dd>{{ solution.best_judgement.score }} {% trans 'of' %} {{ solution.best_judgement.max_score }}</dd>
                        {% endif %}
                    {% endif %}

                    {% if solution_environment.contest %}
                        <dt>{% trans 'Contest' %}</dt>
                        <dd><a href="{% url 'contests:standings' solution_environment.contest.id %}">{{ solution_environment.contest }}</a></dd>
                    {% endif %}
                </dl>
            </div>

            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>{% trans 'Submitted' %}</dt>
                    <dd>{{ solution.reception_time }}</dd>

                    {% if extra_info and extra_info.finish_testing_time %}
                        <dt>{% trans 'Judged' %}</dt>
                        <dd>{{ extra_info.finish_testing_time }}</dd>
                    {% endif %}

                    {% if solution_permissions.ip_address and solution.ip_address %}
                        <dt>{% trans 'IP address' %}</dt>
                        <dd><tt>{{ solution.ip_address }}</tt></dd>
                    {% endif %}

                    <dt>{% trans 'File' %}</dt>
                    <dd>
                        <span class="ir-monospace">{{ solution.source_code.filename }}</span>
                        <span class="ir-file-size">({{ solution.source_code.size|filesizeformat }})</span>
                    </dd>

                    <dt>{% trans 'Compiler' %}</dt>
                    <dd>{% irunner_proglangs_compilerbox solution.compiler tooltip=False %} {{ solution.compiler }}</dd>
                </dl>
            </div>
        </div>
        <div class="row">
            <div class="span12 text-center">
                <ul class="nav nav-pills ir-solution-nav-pills">
                    {% if solution_permissions.attempts %}
                        <li role="presentation"{% if active_tab == 'attempts' %} class="active"{% endif %}>
                            <a href="{% url 'solutions:attempts' solution.id %}">{% trans 'Attempts' %} ({{ attempt_count }})</a>
                        </li>
                    {% endif %}

                    {% if solution_permissions.judgements %}
                        <li role="presentation"{% if active_tab == 'judgements' %} class="active"{% endif %}>
                            <a href="{% url 'solutions:judgements' solution.id %}">{% trans 'Judgements' %} ({{ judgement_count }})</span></a>
                        </li>
                    {% endif %}

                    {% if solution_permissions.source_code %}
                        <li role="presentation"{% if active_tab == 'source' %} class="active"{% endif %}>
                            <a href="{% url 'solutions:source' solution.id %}">{% trans 'Source code' %}</a>
                        </li>
                    {% endif %}

                    {% if solution_permissions.compilation_log %}
                        <li role="presentation"{% if active_tab == 'log' %} class="active"{% endif %}>
                            <a href="{% url 'solutions:log' solution.id %}">{% trans 'Compilation log' %}</a>
                        </li>
                    {% endif %}

                    {% if solution_permissions.results %}
                        <li role="presentation"{% if active_tab == 'tests' %} class="active"{% endif %}>
                            <a href="{% url 'solutions:tests' solution.id %}">{% trans 'Test results' %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% block main %}
{% endblock %}

{% endblock %}